### ISSUE TITLE
can you add manga section too

### ISSUE THREAD

**Issue by helloanime** [codeblitz97/izel#4]
@devaoto 
can you add manga section too. if it is possible
@devaoto

**Comment by sulvii** [comment]
I'm working on it :3

**Comment by helloanime** [comment]
@devaoto 
oky . if it is possible then add multi language subtitle 
@devaoto

**Comment by sulvii** [comment]
multi language subtitle is available

**Comment by helloanime** [comment]
@devaoto 
there is no api or .emv to add api is all will use sape api it will decrease the speed of website or not??
@devaoto

**Comment by helloanime** [comment]
> multi language subtitle is available

only english is available
